SaveUploader:
  isEnabled: true
  tencent-cos:
    secret-id: "xxxxxx"
    secret-key: "xxxxxx"
    region: "ap-nanjing"
    bucket: "meta-world-backup-1258860419"
  world-folder: "/mnt/meta/worlds"
  interval-second: 1